file.directory=files
spring.servlet.multipart.max-file-size=10MB
datasource.url=jdbc:postgresql://10.45.190.204:5432/postgres
datasource.username=postgres
datasource.password=password
spring.main.banner-mode=off
logging.level.org.springframework=ERROR
logging.level.ru.job4j.dreamjob=TRACE